/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [FormList, Npc]
    /// </summary>
    public partial interface IAliasVoiceType :
        IFallout4MajorRecordInternal,
        IAliasVoiceTypeGetter
    {
    }

    /// <summary>
    /// Implemented by: [FormList, Npc]
    /// </summary>
    public partial interface IAliasVoiceTypeGetter : IFallout4MajorRecordGetter
    {
    }
}
