/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [Cell, Worldspace]
    /// </summary>
    public partial interface IComplexLocation :
        IFallout4MajorRecordInternal,
        IComplexLocationGetter
    {
    }

    /// <summary>
    /// Implemented by: [Cell, Worldspace]
    /// </summary>
    public partial interface IComplexLocationGetter : IFallout4MajorRecordGetter
    {
    }
}
