/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [DialogResponses, DialogTopic]
    /// </summary>
    public partial interface IDialog :
        IFallout4MajorRecordInternal,
        IDialogGetter
    {
    }

    /// <summary>
    /// Implemented by: [DialogResponses, DialogTopic]
    /// </summary>
    public partial interface IDialogGetter : IFallout4MajorRecordGetter
    {
    }
}
