/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [ObjectEffect, Spell]
    /// </summary>
    public partial interface IEffectRecord :
        IFallout4MajorRecordInternal,
        IEffectRecordGetter
    {
    }

    /// <summary>
    /// Implemented by: [ObjectEffect, Spell]
    /// </summary>
    public partial interface IEffectRecordGetter : IFallout4MajorRecordGetter
    {
    }
}
