/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [Light, Region]
    /// </summary>
    public partial interface IEmittance :
        IFallout4MajorRecordInternal,
        IEmittanceGetter
    {
    }

    /// <summary>
    /// Implemented by: [Light, Region]
    /// </summary>
    public partial interface IEmittanceGetter : IFallout4MajorRecordGetter
    {
    }
}
