/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [Activator, Ammunition, Armor, Book, Container, Door, Faction, FormList, Furniture, IdleMarker, Ingestible, Key, Light, MiscItem, MoveableStatic, Npc, Projectile, Scroll, Shout, SoundMarker, Spell, Static, TextureSet, Weapon]
    /// </summary>
    public partial interface IObjectId :
        IFallout4MajorRecordInternal,
        IObjectIdGetter
    {
    }

    /// <summary>
    /// Implemented by: [Activator, Ammunition, Armor, Book, Container, Door, Faction, FormList, Furniture, IdleMarker, Ingestible, Key, Light, MiscItem, MoveableStatic, Npc, Projectile, Scroll, Shout, SoundMarker, Spell, Static, TextureSet, Weapon]
    /// </summary>
    public partial interface IObjectIdGetter : IFallout4MajorRecordGetter
    {
    }
}
