/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [PlacedNpc, PlacedObject, APlaced, APlacedTrap]
    /// </summary>
    public partial interface IPlaced :
        IFallout4MajorRecordInternal,
        IPlacedGetter
    {
    }

    /// <summary>
    /// Implemented by: [PlacedNpc, PlacedObject, APlaced, APlacedTrap]
    /// </summary>
    public partial interface IPlacedGetter : IFallout4MajorRecordGetter
    {
    }
}
