/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [LeveledSpell, Spell]
    /// </summary>
    public partial interface ISpellSpawn :
        IFallout4MajorRecordInternal,
        ISpellSpawnGetter
    {
    }

    /// <summary>
    /// Implemented by: [LeveledSpell, Spell]
    /// </summary>
    public partial interface ISpellSpawnGetter : IFallout4MajorRecordGetter
    {
    }
}
